import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ChakraProvider } from "@chakra-ui/react";
import NavBar from "../components/navbar/Navbar";
import Footer from "../components/footer/Footer";
import theme from "../styles/theme";

const Home: NextPage = () => {
  const navOptions = [
    {
      optionName: "Login",
      optionLink: "/login",
      optionColor: "blue"
    }
  ];

  const footerLinkOptions = [
    {
      footerHeader: "Page1",
      footerLinks: [
        {
          footerLinkName: "Page 123",
          footerLinkUrl: "google.com"
        },
        {
          footerLinkName: "Page 123",
          footerLinkUrl: "google.com"
        },
        {
          footerLinkName: "Page 123",
          footerLinkUrl: "google.com"
        }
      ]
    },
    {
      footerHeader: "Page2",
      footerLinks: [
        {
          footerLinkName: "Page 123",
          footerLinkUrl: "google.com"
        },
        {
          footerLinkName: "Page 123",
          footerLinkUrl: "google.com"
        },
        {
          footerLinkName: "Page 123",
          footerLinkUrl: "google.com"
        }
      ]
    }
  ];

  const footerOptions = {
    footerLogo: "https://drive.google.com/file/d/11OyJy750MXgmQR_0JTQ1-lMadGaERVRW/view?usp=sharing",
    footerBGColor: "darkBlue",
    footerLinkColor: "White",
    footerLinkInfo: footerLinkOptions
  };
  return (
    <ChakraProvider theme={theme}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <NavBar navColor='red' navOptions={navOptions} />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href='https://nextjs.org/docs' className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href='https://nextjs.org/learn' className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href='https://github.com/vercel/next.js/tree/canary/examples' className={styles.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
          </a>
        </div>
      </main>

      <Footer
        footerLogo={footerOptions.footerLogo}
        footerLinkColor={footerOptions.footerLinkColor}
        footerBGColor={footerOptions.footerBGColor}
        footerLinkInfo={footerOptions.footerLinkInfo}
      />
    </ChakraProvider>
  );
};

export default Home;
