import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ChakraProvider, Container } from "@chakra-ui/react";
import NavBar from "../components/navbar/Navbar";
import Footer from "../components/footer/Footer";
import theme from "../styles/theme";
import React, { useState } from "react";
import LoginComponent from "../components/forms/login/Login";
import { getTherapyDetailsById } from "../util/graphql-queries";
import client from "../util/apollo-client";

const Home: NextPage = ({ token }) => {
  const navOptions = [
    {
      optionName: "Login",
      optionLink: "/login",
      optionColor: "blue"
    },
    {
      optionName: "About",
      optionLink: "/about",
      optionColor: "blue"
    }
  ];

  const accountOptions = [
    {
      optionName: "Account Settings",
      optionLink: "/login",
      optionColor: "blue"
    },
    {
      optionName: "Logout",
      optionLink: "/about",
      optionColor: "blue"
    }
  ];

  const footerLinkOptions = [
    {
      footerHeader: "Page1",
      footerLinks: [
        {
          footerLinkName: "Page 123",
          footerLinkUrl: "google.com"
        },
        {
          footerLinkName: "Page 123",
          footerLinkUrl: "google.com"
        },
        {
          footerLinkName: "Page 123",
          footerLinkUrl: "google.com"
        }
      ]
    },
    {
      footerHeader: "Page2",
      footerLinks: [
        {
          footerLinkName: "Page 123",
          footerLinkUrl: "google.com"
        },
        {
          footerLinkName: "Page 123",
          footerLinkUrl: "google.com"
        },
        {
          footerLinkName: "Page 123",
          footerLinkUrl: "google.com"
        }
      ]
    }
  ];

  const footerOptions = {
    footerLogo: "https://drive.google.com/file/d/11OyJy750MXgmQR_0JTQ1-lMadGaERVRW/view?usp=sharing",
    footerBGColor: "darkBlue",
    footerLinkColor: "White",
    footerLinkInfo: footerLinkOptions
  };

  const [userEmail, setUserEmail] = useState("");
  const [userPassword, setUserPassword] = useState("");
  const [forgotPassword, setForgotPassword] = useState(false);

  return (
    <ChakraProvider theme={theme}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <NavBar
        navColor='white'
        navOptions={navOptions}
        isAuthenticated={true}
        protectedNavOptions={navOptions}
        accountOptions={accountOptions}
      />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.tsx</code>
        </p>
        <Container>
          <LoginComponent
            userEmail={userEmail}
            userPassword={userPassword}
            setUserEmail={(e) => setUserEmail(e.target.value)}
            setUserPassword={(e) => setUserPassword(e.target.value)}
            forgotPassword={forgotPassword}
            setForgotPassword={() => setForgotPassword(!forgotPassword)}
          />
        </Container>
      </main>

      <Footer
        footerLogo={footerOptions.footerLogo}
        footerLinkColor={footerOptions.footerLinkColor}
        footerBGColor={footerOptions.footerBGColor}
        footerLinkInfo={footerOptions.footerLinkInfo}
      />
    </ChakraProvider>
  );
};

export async function getServerSideProps() {
  const { data } = await client.query({ query: getTherapyDetailsById(1) });
  console.log(data);
  return {
    props: {
      token: data
    }
  };
}

export default Home;
